"""comment

Revision ID: 88a8b238970b
Revises: 8d49fe123be2
Create Date: 2023-09-27 23:07:07.467020

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '88a8b238970b'
down_revision = '8d49fe123be2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('allowedpublicdid', sa.Column('registered_did', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.drop_column('allowedpublicdid', 'author_did')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('allowedpublicdid', sa.Column('author_did', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('allowedpublicdid', 'registered_did')
    # ### end Alembic commands ###
