"""make connection_id unique

Revision ID: f4e857e3d8eb
Revises: b1e41d72f00e
Create Date: 2024-09-16 17:33:30.156800

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = 'f4e857e3d8eb'
down_revision = 'b1e41d72f00e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('contact', 'connection_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.create_unique_constraint(None, 'contact', ['connection_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'contact', type_='unique')
    op.alter_column('contact', 'connection_id',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###
