"""make connection_id unique

Revision ID: 30a321309310
Revises: 9a8ef028a751
Create Date: 2024-09-03 16:57:54.926251

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '30a321309310'
down_revision = '9a8ef028a751'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('contact', 'connection_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.create_unique_constraint(None, 'contact', ['connection_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'contact', type_='unique')
    op.alter_column('contact', 'connection_id',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###
