"""rename author_did to creddef_author_did and issuer_did to schema_issuer_did

Revision ID: b1e41d72f00e
Revises: 9a8ef028a751
Create Date: 2024-09-12 00:02:34.371864

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = 'b1e41d72f00e'
down_revision = '9a8ef028a751'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('allowedcredentialdefinition', 'issuer_did',  nullable=False, new_column_name='schema_issuer_did')
    op.alter_column('allowedcredentialdefinition', 'author_did',  nullable=False, new_column_name='creddef_author_did')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('allowedcredentialdefinition', 'schema_issuer_did',  nullable=False, new_column_name='issuer_did')
    op.alter_column('allowedcredentialdefinition', 'creddef_author_did',  nullable=False, new_column_name='author_did')
    # ### end Alembic commands ###
