 # For details on how this file works refer to:
 #   - https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file
version: 2
updates:
  # Maintain dependencies for Python Packages
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "04:00"
      timezone: "Canada/Pacific"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]

  # Maintain dependencies for docker
  - package-ecosystem: "docker"
    directory: "/docker/acapy"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "04:00"
      timezone: "Canada/Pacific"

  # Maintain dependencies for docker
  - package-ecosystem: "docker"
    directory: "/endorser"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "04:00"
      timezone: "Canada/Pacific"
  
  # Maintain dependencies for dev Container
  - package-ecosystem: "devcontainers"
    directory: "/.devcontainer"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "04:00"
      timezone: "Canada/Pacific"

