#!/bin/bash

psql -U ${POSTGRES_USER} <<-END
    CREATE DATABASE ${CONTROLLER_POSTGRESQL_DB};
    CREATE USER ${CONTROLLER_POSTGRESQL_ADMIN_USER} PASSWORD '${CONTROLLER_POSTGRESQL_ADMIN_PASSWORD}';
    CREATE USER ${CONTROLLER_POSTGRESQL_USER} PASSWORD '${CONTROLLER_POSTGRESQL_PASSWORD}';
    ALTER DATABASE ${CONTROLLER_POSTGRESQL_DB} OWNER TO ${CONTROLLER_POSTGRESQL_ADMIN_USER};
    \connect ${CONTROLLER_POSTGRESQL_DB}
    CREATE EXTENSION IF NOT EXISTS pgcrypto;
    REVOKE ALL ON SCHEMA public FROM PUBLIC;
    GRANT USAGE ON SCHEMA public TO ${CONTROLLER_POSTGRESQL_ADMIN_USER};
    GRANT USAGE ON SCHEMA public TO ${CONTROLLER_POSTGRESQL_USER};
    GRANT ALL ON SCHEMA public TO ${CONTROLLER_POSTGRESQL_ADMIN_USER};
    ALTER DEFAULT PRIVILEGES FOR USER ${CONTROLLER_POSTGRESQL_ADMIN_USER} IN SCHEMA public GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO ${CONTROLLER_POSTGRESQL_USER};
    ALTER DEFAULT PRIVILEGES FOR USER ${CONTROLLER_POSTGRESQL_ADMIN_USER} IN SCHEMA public GRANT USAGE, SELECT ON SEQUENCES TO ${CONTROLLER_POSTGRESQL_USER};
    ALTER DEFAULT PRIVILEGES FOR USER ${CONTROLLER_POSTGRESQL_ADMIN_USER} IN SCHEMA public GRANT EXECUTE ON FUNCTIONS TO ${CONTROLLER_POSTGRESQL_USER};
END
