FROM python:3.12-slim-bullseye

RUN apt-get update -y && \
    apt-get install -y --no-install-recommends \
    build-essential curl && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

WORKDIR /app

ENV POETRY_VIRTUALENVS_CREATE=false
RUN pip install --no-cache-dir poetry

ADD pyproject.toml poetry.lock ./
RUN poetry install --no-dev

ADD ./endorser .

EXPOSE 5000
ENTRYPOINT ["./docker-entrypoint.sh"]
